# Generated by Django 4.2.1 on 2023-05-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(default='pp', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
