# Generated by Django 4.2.1 on 2023-06-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(blank=True, choices=[('', ''), ('A1', 'Начальный'), ('A2', 'Элементарный'), ('B1', 'Средний'), ('B2', 'Средне-продвинутый'), ('C1', 'Продвинутый'), ('C2', 'В совершенстве')], max_length=200, null=True),
        ),
    ]
