# Generated by Django 4.2.1 on 2023-06-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_experience_work_here'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endwork',
            name='month',
            field=models.CharField(choices=[('', 'Месяц'), ('January,', 'Январь'), ('February', 'Февраль'), ('March', 'Март'), ('April', 'Апрель'), ('May', 'Май'), ('June', 'Июнь'), ('July', 'Июль'), ('August', 'Август'), ('September', 'Сентябрь'), ('October', 'Октябрь'), ('November', 'Ноябрь'), ('December', 'Декабрь')], max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='organization',
            field=models.CharField(max_length=250, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='startwork',
            name='month',
            field=models.CharField(choices=[('', 'Месяц'), ('January,', 'Январь'), ('February', 'Февраль'), ('March', 'Март'), ('April', 'Апрель'), ('May', 'Май'), ('June', 'Июнь'), ('July', 'Июль'), ('August', 'Август'), ('September', 'Сентябрь'), ('October', 'Октябрь'), ('November', 'Ноябрь'), ('December', 'Декабрь')], max_length=200),
        ),
    ]
