# Generated by Django 4.2.1 on 2023-06-26 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_amount_of_work_alter_task_contract_work_and_more'),
        ('users', '0006_alter_customer_owner_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task'),
        ),
    ]
