# Generated by Django 4.2.1 on 2023-07-01 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_message_options_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_feedback', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.profile'),
        ),
    ]
