# Generated by Django 4.2.1 on 2023-07-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_feedback_sender_alter_feedback_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='customer_invited',
            field=models.ManyToManyField(blank=True, related_name='invited_talent', to='users.customer'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='customer_saved',
            field=models.ManyToManyField(blank=True, related_name='saved_talent', to='users.customer'),
        ),
    ]
