# Generated by Django 4.2.1 on 2023-07-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_freelancer_customer_invited_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created']},
        ),
    ]
