# Generated by Django 4.2.1 on 2023-06-01 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('talents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('experiences', models.CharField(choices=[('junior', 'Новичок'), ('middle', 'Средний'), ('senior', 'Эксперт')], max_length=200)),
                ('amount_of_work', models.CharField(choices=[('tiny', 'Менее 1 месяца'), ('little', 'От 1 до 3 месяцев'), ('medium', 'От 3 до 6 месяцев'), ('big', 'Более 6 месяцев')], max_length=200)),
                ('contract_work', models.BooleanField()),
                ('description', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('skills', models.ManyToManyField(blank=True, to='talents.skills')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('hourly_rate', 'Почасовая ставка'), ('fix', 'Бюджет проекта')], max_length=250)),
                ('min_price', models.IntegerField(blank=True, null=True)),
                ('max_price', models.IntegerField(blank=True, null=True)),
                ('fix_price', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
