# Generated by Django 4.2.1 on 2023-06-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='currency',
            field=models.CharField(choices=[('ruble', '₽'), ('dollar', '$'), ('euro', '€')], default='ruble', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
