# Generated by Django 4.2.1 on 2023-06-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_endwork_month_alter_experience_organization_and_more'),
        ('tasks', '0002_budget_currency_alter_task_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='freelancer_saved',
            field=models.ManyToManyField(blank=True, to='users.freelancer'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.CharField(choices=[('hourly_rate', 'Почасовая ставка'), ('fix', 'Фиксированная цена')], max_length=250),
        ),
        migrations.AlterField(
            model_name='task',
            name='experiences',
            field=models.CharField(choices=[('junior', 'Начальный уровень'), ('middle', 'Средний уровень'), ('senior', 'Эксперт')], max_length=200),
        ),
    ]
