# Generated by Django 4.2.1 on 2023-06-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0005_talent_customer_invited_talent_customer_saved'),
        ('users', '0006_alter_customer_owner_message'),
        ('tasks', '0004_task_freelancer_responded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='amount_of_work',
            field=models.CharField(choices=[('tiny', 'Менее 1 месяца'), ('little', 'От 1 до 3 месяцев'), ('medium', 'От 3 до 6 месяцев'), ('big', 'Более 6 месяцев')], max_length=200, verbose_name='Объем работы'),
        ),
        migrations.AlterField(
            model_name='task',
            name='contract_work',
            field=models.BooleanField(verbose_name='Работа по контракту'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='experiences',
            field=models.CharField(choices=[('junior', 'Начальный уровень'), ('middle', 'Средний уровень'), ('senior', 'Эксперт')], max_length=200, verbose_name='Уровень опыта'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.customer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='skills',
            field=models.ManyToManyField(blank=True, to='talents.skills', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
