# Generated by Django 4.2.1 on 2023-07-04 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_freelancer_customer_invited_and_more'),
        ('tasks', '0006_work_stagesofwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('at_work', models.BooleanField(default=False)),
                ('prospective_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospective_employee', to='users.freelancer')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
