# Generated by Django 4.2.1 on 2023-07-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_stagesofwork_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagesofwork',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
