# Generated by Django 4.2.1 on 2023-07-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_feedback_options'),
        ('tasks', '0009_stagesofwork_update_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stagesofwork',
            options={'ordering': ['max_term']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-time_updated']},
        ),
        migrations.AddField(
            model_name='task',
            name='freelancer_refused',
            field=models.ManyToManyField(blank=True, related_name='refused_tasks', to='users.freelancer'),
        ),
    ]
