# Generated by Django 4.2.1 on 2023-06-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0002_hourlyrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
