# Generated by Django 4.2.1 on 2023-06-16 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_endwork_month_alter_experience_organization_and_more'),
        ('talents', '0003_alter_talent_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyrate',
            name='currency',
            field=models.CharField(choices=[('ruble', '₽'), ('dollar', '$'), ('euro', '€')], default='ruble', max_length=200, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='hourlyrate',
            name='rate',
            field=models.IntegerField(verbose_name='Почасовая ставка'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='descriptions',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.services', verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='skills',
            field=models.ManyToManyField(blank=True, to='talents.skills', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Ваш заголовок'),
        ),
    ]
