# Generated by Django 4.2.1 on 2023-06-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_endwork_month_alter_experience_organization_and_more'),
        ('talents', '0004_alter_hourlyrate_currency_alter_hourlyrate_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='customer_invited',
            field=models.ManyToManyField(blank=True, related_name='invited_talent', to='users.customer'),
        ),
        migrations.AddField(
            model_name='talent',
            name='customer_saved',
            field=models.ManyToManyField(blank=True, related_name='saved_talent', to='users.customer'),
        ),
    ]
