# Generated by Django 4.2.1 on 2023-07-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0005_talent_customer_invited_talent_customer_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='customer_invited',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='customer_saved',
        ),
    ]
