# Generated by Django 4.2.1 on 2023-07-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0006_remove_talent_customer_invited_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talent',
            options={'ordering': ['-time_updated']},
        ),
    ]
